# Generated by Django 5.0.2 on 2025-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccUsers',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pass_field', models.CharField(db_column='pass', max_length=100)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('accountcode', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'acc_users',
                'managed': False,
            },
        ),
    ]
