# Generated by Django 5.0.2 on 2025-07-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('phones', models.CharField(blank=True, max_length=60, null=True)),
                ('mobile', models.CharField(blank=True, max_length=60, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('address3', models.CharField(blank=True, max_length=50, null=True)),
                ('pagers', models.CharField(blank=True, max_length=60, null=True)),
                ('tinno', models.CharField(blank=True, max_length=30, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'misel',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='accusers',
            options={'managed': True},
        ),
    ]
