# Generated by Django 5.0.2 on 2025-07-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accusers',
            options={},
        ),
    ]
