# Generated by Django 5.0.2 on 2025-07-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_accusers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accusers',
            options={'managed': True},
        ),
    ]
