# Generated by Django 5.0.2 on 2025-08-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_accinvmast_accledgers_cashandbankaccmaster_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashandbankaccmaster',
            unique_together={('code', 'client_id')},
        ),
    ]
