# Generated by Django 5.0.2 on 2025-08-11 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_cashandbankaccmaster_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='accmaster',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accmaster',
            name='id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accmaster',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cashandbankaccmaster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
