# Generated by Django 5.0.2 on 2025-10-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_accmaster_area_accmaster_id_alter_accmaster_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accledgers',
            name='super_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='accmaster',
            name='super_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='AccTtServicemaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slno', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_tt_servicemaster',
                'managed': True,
                'unique_together': {('slno', 'client_id')},
            },
        ),
    ]
