# Generated by Django 4.2.7 on 2025-11-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_accledgers_super_code_accmaster_super_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccInvmast',
        ),
        migrations.DeleteModel(
            name='AccLedgers',
        ),
        migrations.DeleteModel(
            name='AccTtServicemaster',
        ),
        migrations.DeleteModel(
            name='CashAndBankAccMaster',
        ),
        migrations.DeleteModel(
            name='Misel',
        ),
    ]
